In [1]:
import gym
import keras

print(gym.__version__)
print(keras.__version__)
print(keras.backend.backend())

Using Theano backend.


0.15.3
2.2.4
theano


In [2]:
import math
import random
import numpy as np
from collections import deque

In [5]:
#using gym to run an environment 

env = gym.make('CartPole-v0')
for i_epsd in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episodes finished after {} time steps".format(t+1))
env.reset()

[-0.02690064  0.0238192  -0.02826297  0.03227096]
[-0.02642425 -0.17088628 -0.02761755  0.31590435]
[-0.02984198 -0.36560419 -0.02129946  0.59975129]
[-0.03715406 -0.56042177 -0.00930444  0.88564982]
[-0.0483625  -0.75541618  0.00840856  1.1753933 ]
[-0.06347082 -0.56040449  0.03191642  0.88535819]
[-0.07467891 -0.36573005  0.04962359  0.60287709]
[-0.08199351 -0.17133602  0.06168113  0.32622834]
[-0.08542023 -0.36727945  0.0682057   0.6377073 ]
[-0.09276582 -0.17317156  0.08095984  0.36725939]
[-0.09622925 -0.36934501  0.08830503  0.68433192]
[-0.10361615 -0.56557485  0.10199167  1.00345776]
[-0.11492765 -0.76190045  0.12206082  1.3263494 ]
[-0.13016566 -0.95833354  0.14858781  1.65460364]
[-0.14933233 -1.15484469  0.18167988  1.98964661]
Episodes finished after 15 time steps
[-0.17242923 -0.96203409  0.22147282  1.75831128]
Episodes finished after 16 time steps
[-0.19166991 -0.77000098  0.25663904  1.54187925]
Episodes finished after 17 time steps
[-0.20706993 -0.57871319  0.28747663

[-0.0803066  -0.38997542  0.10469432  0.57109119]
[-0.08810611 -0.19646537  0.11611615  0.31313937]
[-0.09203541 -0.39303353  0.12237893  0.64006759]
[-0.09989608 -0.58962995  0.13518028  0.96864637]
[-0.11168868 -0.39655637  0.15455321  0.72130018]
[-0.11961981 -0.59344019  0.16897922  1.05836371]
[-0.13148861 -0.40091044  0.19014649  0.8231262 ]
[-0.13950682 -0.20882734  0.20660901  0.59576136]
Episodes finished after 18 time steps
[-0.14368337 -0.40615012  0.21852424  0.9457624 ]
Episodes finished after 19 time steps
[-0.15180637 -0.21453306  0.23743949  0.72890827]
Episodes finished after 20 time steps
[-0.15609703 -0.02334186  0.25201765  0.51932084]
Episodes finished after 21 time steps
[-0.15656387 -0.22096228  0.26240407  0.87969897]
Episodes finished after 22 time steps
[-0.16098312 -0.03017671  0.27999805  0.67958126]
Episodes finished after 23 time steps
[-0.16158665  0.16019695  0.29358968  0.48638965]
Episodes finished after 24 time steps
[-0.15838271 -0.03761873  0.303317

[-0.10442166 -0.41604938  0.15201379  0.83670216]
[-0.11274265 -0.22329409  0.16874783  0.5954236 ]
[-0.11720853 -0.03088557  0.1806563   0.36028706]
[-0.11782624  0.16127036  0.18786204  0.12956841]
[-0.11460084 -0.03597641  0.19045341  0.47514009]
[-0.11532036  0.15601799  0.19995621  0.24801123]
[-0.1122     -0.04131423  0.20491644  0.59650803]
Episodes finished after 23 time steps
[-0.11302629  0.15044018  0.2168466   0.37471895]
Episodes finished after 24 time steps
[-0.11001749 -0.04699688  0.22434098  0.72719325]
Episodes finished after 25 time steps
[-0.11095742  0.14443611  0.23888484  0.51264385]
Episodes finished after 26 time steps
[-0.1080687   0.33553873  0.24913772  0.30369625]
Episodes finished after 27 time steps
[-0.10135793  0.52640682  0.25521165  0.09872469]
Episodes finished after 28 time steps
[-0.09082979  0.7171385   0.25718614 -0.10388574]
Episodes finished after 29 time steps
[-0.07648702  0.90783245  0.25510842 -0.30573674]
Episodes finished after 30 time st

[-0.56916229 -2.33987816  1.1141076   5.32048579]
Episodes finished after 25 time steps
[-0.61595985 -2.1375699   1.22051731  5.45053555]
Episodes finished after 26 time steps
[-0.65871125 -1.93304942  1.32952803  5.62140815]
Episodes finished after 27 time steps
[-0.69737224 -2.09068634  1.44195619  5.96338997]
Episodes finished after 28 time steps
[-0.73918596 -2.24231682  1.56122399  6.2841763 ]
Episodes finished after 29 time steps
[-0.7840323  -2.02472604  1.68690751  6.5750386 ]
Episodes finished after 30 time steps
[-0.82452682 -2.16609943  1.81840829  6.84249174]
Episodes finished after 31 time steps
[-0.86784881 -1.93891018  1.95525812  7.21104741]
Episodes finished after 32 time steps
[-0.90662701 -2.07355229  2.09947907  7.40783718]
Episodes finished after 33 time steps
[-0.94809806 -1.83876475  2.24763581  7.83933699]
Episodes finished after 34 time steps
[-0.98487335 -1.97412599  2.40442255  7.94135481]
Episodes finished after 35 time steps
[-1.02435587 -1.7383052   2.5632

[-0.2368987   0.07480245  0.65236828  2.02952834]
Episodes finished after 32 time steps
[-0.23540265  0.26043962  0.69295885  1.98673254]
Episodes finished after 33 time steps
[-0.23019386  0.06651957  0.7326935   2.39833584]
Episodes finished after 34 time steps
[-0.22886346 -0.12568767  0.78066022  2.80930812]
Episodes finished after 35 time steps
[-0.23137722  0.06092012  0.83684638  2.81734722]
Episodes finished after 36 time steps
[-0.23015881 -0.12796435  0.89319333  3.22542681]
Episodes finished after 37 time steps
[-0.2327181  -0.31392483  0.95770186  3.62935122]
Episodes finished after 38 time steps
[-0.2389966  -0.12432174  1.03028889  3.70615867]
Episodes finished after 39 time steps
[-0.24148303  0.06573828  1.10441206  3.81154918]
Episodes finished after 40 time steps
[-0.24016827  0.25661725  1.18064304  3.94540411]
Episodes finished after 41 time steps
[-0.23503592  0.08145857  1.25955112  4.31723743]
Episodes finished after 42 time steps
[-0.23340675 -0.08921688  1.3458

[-0.30013011 -2.13566439  0.77019521  4.65787621]
Episodes finished after 36 time steps
[-0.3428434  -2.31679083  0.86335273  5.05759315]
Episodes finished after 37 time steps
[-0.38917922 -2.11818044  0.9645046   5.08742747]
Episodes finished after 38 time steps
[-0.43154283 -1.91887217  1.06625315  5.15867093]
Episodes finished after 39 time steps
[-0.46992027 -1.71833588  1.16942657  5.27062602]
Episodes finished after 40 time steps
[-0.50428699 -1.51597067  1.27483909  5.42267094]
Episodes finished after 41 time steps
[-0.5346064  -1.31112263  1.3832925   5.6142712 ]
Episodes finished after 42 time steps
[-0.56082885 -1.46760661  1.49557793  5.94687272]
Episodes finished after 43 time steps
[-0.59018099 -1.25464848  1.61451538  6.21603651]
Episodes finished after 44 time steps
[-0.61527396 -1.4008093   1.73883611  6.50017362]
Episodes finished after 45 time steps
[-0.64329014 -1.54282464  1.86883959  6.75440437]
Episodes finished after 46 time steps
[-0.67414663 -1.6820642   2.0039

[ 0.29917599 -0.92717154 -0.07599902  0.91094136]
[ 0.28063256 -0.73110802 -0.05778019  0.59537277]
[ 0.2660104  -0.92537573 -0.04587274  0.86931012]
[ 0.24750289 -0.72966074 -0.02848654  0.56256461]
[ 0.23290967 -0.53415087 -0.01723524  0.26104488]
[ 0.22222665 -0.7290226  -0.01201435  0.54824215]
[ 0.2076462  -0.92397373 -0.0010495   0.8371156 ]
[ 0.18916673 -1.11908133  0.01569281  1.12946829]
[ 0.1667851  -0.92416838  0.03828217  0.84174836]
[ 0.14830173 -0.72958932  0.05511714  0.56134582]
[ 0.13370995 -0.53528244  0.06634406  0.28652434]
[ 0.1230043  -0.34116628  0.07207454  0.01548153]
[ 0.11618097 -0.14714801  0.07238418 -0.25361872]
[ 0.11323801 -0.34322486  0.0673118   0.06098875]
[ 0.10637351 -0.14912935  0.06853158 -0.20972047]
[ 0.10339093 -0.34516087  0.06433717  0.10376909]
[ 0.09648771 -0.54114302  0.06641255  0.41603618]
[ 0.08566485 -0.34702207  0.07473327  0.14500761]
[ 0.07872441 -0.15304551  0.07763342 -0.12319395]
[ 0.0756635   0.04088333  0.07516954 -0.39040974]


[ 2.11652697  1.62675523 -7.44524897 -6.90863626]
Episodes finished after 77 time steps
[ 2.14906208  1.77523036 -7.58342169 -7.26693452]
Episodes finished after 78 time steps
[ 2.18456669  1.9149095  -7.72876038 -7.60623749]
Episodes finished after 79 time steps
[ 2.22286488  2.04633994 -7.88088513 -7.92255785]
Episodes finished after 80 time steps
[ 2.26379168  2.17076471 -8.03933629 -8.21143087]
Episodes finished after 81 time steps
[ 2.30720697  2.29019095 -8.20356491 -8.46738042]
Episodes finished after 82 time steps
[ 2.35301079  2.04084171 -8.37291252 -8.87170352]
Episodes finished after 83 time steps
[ 2.39382762  1.7868771  -8.55034659 -9.31592979]
Episodes finished after 84 time steps
[ 2.42956516  1.53077031 -8.73666518 -9.78789348]
Episodes finished after 85 time steps
[  2.46018057   1.27675093  -8.93242305 -10.26893152]
Episodes finished after 86 time steps
[  2.48571559   1.41500725  -9.13780168 -10.22515422]
Episodes finished after 87 time steps
[  2.51401573   1.576417

[-0.12261647  0.54175185  7.22715834  6.72335606]
Episodes finished after 77 time steps
[-0.11178144  0.75551817  7.36162546  6.77338024]
Episodes finished after 78 time steps
[-0.09667107  0.60255678  7.49709307  7.14091745]
Episodes finished after 79 time steps
[-0.08461994  0.82528993  7.63991142  7.29967076]
Episodes finished after 80 time steps
[-0.06811414  1.05236808  7.78590483  7.51459965]
Episodes finished after 81 time steps
[-0.04706678  0.92081818  7.93619682  7.82134152]
Episodes finished after 82 time steps
[-0.02865041  0.79546042  8.09262366  8.0989064 ]
Episodes finished after 83 time steps
[-0.01274121  0.67418909  8.25460178  8.34157462]
Episodes finished after 84 time steps
[7.42576173e-04 5.54172933e-01 8.42143328e+00 8.54208794e+00]
Episodes finished after 85 time steps
[0.01182603 0.43194178 8.59227503 8.69146424]
Episodes finished after 86 time steps
[0.02046487 0.30360488 8.76610432 8.77935076]
Episodes finished after 87 time steps
[0.02653697 0.16524308 8.941

[ 1.15608175 -0.42475836 -6.5983802  -1.71380888]
Episodes finished after 84 time steps
[ 1.14758658 -0.6152026  -6.63265637 -1.53335611]
Episodes finished after 85 time steps
[ 1.13528253 -0.80486922 -6.6633235  -1.36671895]
Episodes finished after 86 time steps
[ 1.11918515 -0.99382234 -6.69065787 -1.21261069]
Episodes finished after 87 time steps
[ 1.0993087  -1.18213086 -6.71491009 -1.06978375]
Episodes finished after 88 time steps
[ 1.07566608 -0.98455693 -6.73630576 -1.46197292]
Episodes finished after 89 time steps
[ 1.05597495 -0.78746686 -6.76554522 -1.85647946]
Episodes finished after 90 time steps
[ 1.04022561 -0.97529768 -6.80267481 -1.74325782]
Episodes finished after 91 time steps
[ 1.02071965 -0.77900692 -6.83753997 -2.1448023 ]
Episodes finished after 92 time steps
[ 1.00513952 -0.96627575 -6.88043601 -2.06072708]
Episodes finished after 93 time steps
[ 0.985814   -0.77132605 -6.92165056 -2.46786567]
Episodes finished after 94 time steps
[ 0.97038748 -0.57790845 -6.9710

[-0.3161864   0.14475617 -5.85538538 -3.37823127]
Episodes finished after 83 time steps
[-0.31329127  0.33666676 -5.92295001 -3.51818311]
Episodes finished after 84 time steps
[-0.30655794  0.1428329  -5.99331367 -3.1424611 ]
Episodes finished after 85 time steps
[-0.30370128 -0.05229704 -6.05616289 -2.77794348]
Episodes finished after 86 time steps
[-0.30474722 -0.24814358 -6.11172176 -2.42553879]
Episodes finished after 87 time steps
[-0.30971009 -0.05486514 -6.16023254 -2.6610415 ]
Episodes finished after 88 time steps
[-0.3108074   0.13914496 -6.21345337 -2.91380261]
Episodes finished after 89 time steps
[-0.3080245  -0.05632724 -6.27172942 -2.60082231]
Episodes finished after 90 time steps
[-0.30915104  0.13870415 -6.32374587 -2.88998225]
Episodes finished after 91 time steps
[-0.30637696 -0.0561437  -6.38154551 -2.60987238]
Episodes finished after 92 time steps
[-0.30749983 -0.25037963 -6.43374296 -2.34879804]
Episodes finished after 93 time steps
[-0.31250743 -0.05426106 -6.4807

[-0.5054056  -0.4058251   6.02178636  0.98121006]
Episodes finished after 97 time steps
[-0.51352211 -0.59667674  6.04141056  1.18178342]
Episodes finished after 98 time steps
[-0.52545564 -0.78798861  6.06504623  1.39001337]
Episodes finished after 99 time steps
[-0.54121541 -0.59091981  6.09284649  1.03778994]
Episodes finished after 100 time steps
[ 0.00128662 -0.04589888 -0.02824929 -0.03185789]
[ 0.00036864 -0.24060458 -0.02888645  0.25177993]
[-0.00444345 -0.43530239 -0.02385085  0.53521337]
[-0.0131495  -0.63008097 -0.01314659  0.82028667]
[-0.02575112 -0.4347816   0.00325915  0.52349794]
[-0.03444675 -0.23970567  0.01372911  0.23184379]
[-0.03924087 -0.04478256  0.01836598 -0.0564771 ]
[-0.04013652  0.15007131  0.01723644 -0.3433093 ]
[-0.03713509  0.34494386  0.01037025 -0.63050745]
[-0.03023621  0.53991958 -0.00223989 -0.91990651]
[-0.01943782  0.73507174 -0.02063802 -1.21329253]
[-0.00473639  0.54022212 -0.04490388 -0.92714749]
[ 0.00606806  0.34573432 -0.06344683 -0.6489071

[-0.04443516 -0.53986023  0.05835369  0.83723077]
[-0.05523237 -0.73572853  0.0750983   1.14767939]
[-0.06994694 -0.54166307  0.09805189  0.87945984]
[-0.0807802  -0.73797071  0.11564109  1.20128801]
[-0.09553961 -0.9343826   0.13966685  1.52786085]
[-0.11422727 -0.74119463  0.17022407  1.28182936]
[-0.12905116 -0.54859991  0.19586065  1.04691722]
Episodes finished after 16 time steps
[-0.14002316 -0.74570519  0.216799    1.39413789]
Episodes finished after 17 time steps
[-0.15493726 -0.55383764  0.24468175  1.17631448]
Episodes finished after 18 time steps
[-0.16601401 -0.36258061  0.26820804  0.96919476]
Episodes finished after 19 time steps
[-0.17326563 -0.1718605   0.28759194  0.77125389]
Episodes finished after 20 time steps
[-0.17670284 -0.36955484  0.30301702  1.13900766]
Episodes finished after 21 time steps
[-0.18409393 -0.17937881  0.32579717  0.95447001]
Episodes finished after 22 time steps
[-0.18768151  0.01025743  0.34488657  0.77907797]
Episodes finished after 23 time st

[ 0.01441374 -0.03807435 -0.01436281  0.12921757]
[ 0.01365225  0.15725038 -0.01177846 -0.16796182]
[ 0.01679726  0.35253893 -0.0151377  -0.46433711]
[ 0.02384804  0.54787148 -0.02442444 -0.76175269]
[ 0.03480547  0.74332122 -0.03965949 -1.06201993]
[ 0.04967189  0.93894522 -0.06089989 -1.36688202]
[ 0.0684508   1.13477439 -0.08823753 -1.67797473]
[ 0.09114628  0.9407795  -0.12179703 -1.41402265]
[ 0.10996187  1.13718184 -0.15007748 -1.74216357]
[ 0.13270551  1.33365984 -0.18492075 -2.07752514]
Episodes finished after 32 time steps
[ 0.15937871  1.14083264 -0.22647125 -1.84727303]
Episodes finished after 33 time steps
[ 0.18219536  0.94880956 -0.26341671 -1.63260828]
Episodes finished after 34 time steps
[ 0.20117155  1.1458822  -0.29606888 -1.99457249]
Episodes finished after 35 time steps
[ 0.2240892   1.34264839 -0.33596033 -2.36265821]
Episodes finished after 36 time steps
[ 0.25094216  1.15171317 -0.38321349 -2.18919172]
Episodes finished after 37 time steps
[ 0.27397643  1.348051

[-0.44293715 -0.84188794  1.22621389  4.58291451]
Episodes finished after 33 time steps
[-0.45977491 -1.0113018   1.31787218  4.94547512]
Episodes finished after 34 time steps
[-0.48000095 -1.17553191  1.41678168  5.29176593]
Episodes finished after 35 time steps
[-0.50351159 -1.33447518  1.522617    5.61886029]
Episodes finished after 36 time steps
[-0.53020109 -1.12459853  1.63499421  5.89735743]
Episodes finished after 37 time steps
[-0.55269306 -1.2740511   1.75294135  6.17636987]
Episodes finished after 38 time steps
[-0.57817408 -1.41970861  1.87646875  6.42592985]
Episodes finished after 39 time steps
[-0.60656826 -1.19688079  2.00498735  6.80688629]
Episodes finished after 40 time steps
[-0.63050587 -1.33707735  2.14112507  6.9851401 ]
Episodes finished after 41 time steps
[-0.65724742 -1.47829312  2.28082788  7.11824137]
Episodes finished after 42 time steps
[-0.68681328 -1.2482733   2.4231927   7.566104  ]
Episodes finished after 43 time steps
[-0.71177875 -1.01662831  2.5745

[ 0.6286435   2.31457173 -1.10603116 -5.3855554 ]
Episodes finished after 55 time steps
[ 0.67493493  2.48044578 -1.21374227 -5.75989022]
Episodes finished after 56 time steps
[ 0.72454385  2.273018   -1.32894007 -5.92659893]
Episodes finished after 57 time steps
[ 0.77000421  2.06248182 -1.44747205 -6.13640529]
Episodes finished after 58 time steps
[ 0.81125385  2.21211353 -1.57020016 -6.45578214]
Episodes finished after 59 time steps
[ 0.85549612  1.99241502 -1.6993158  -6.74958562]
Episodes finished after 60 time steps
[ 0.89534442  2.13161666 -1.83430751 -7.01439956]
Episodes finished after 61 time steps
[ 0.93797675  2.26751787 -1.9745955  -7.24515336]
Episodes finished after 62 time steps
[ 0.98332711  2.03453652 -2.11949857 -7.65282111]
Episodes finished after 63 time steps
[ 1.02401784  2.16744724 -2.27255499 -7.79967709]
Episodes finished after 64 time steps
[ 1.06736678  2.30432986 -2.42854854 -7.89165797]
Episodes finished after 65 time steps
[ 1.11345338  2.06971286 -2.5863

[ 1.07517941  1.5495047  -3.86440999 -7.91629017]
Episodes finished after 67 time steps
[ 1.1061695   1.40651911 -4.02273579 -7.88265614]
Episodes finished after 68 time steps
[ 1.13429988  1.64505957 -4.18038891 -7.42818083]
Episodes finished after 69 time steps
[ 1.16720107  1.5099419  -4.32895253 -7.2776226 ]
Episodes finished after 70 time steps
[ 1.19739991  1.37613583 -4.47450498 -7.08005876]
Episodes finished after 71 time steps
[ 1.22492263  1.60617226 -4.61610616 -6.71302715]
Episodes finished after 72 time steps
[ 1.25704607  1.4663229  -4.7503667  -6.44055529]
Episodes finished after 73 time steps
[ 1.28637253  1.32166605 -4.87917781 -6.13852866]
Episodes finished after 74 time steps
[ 1.31280585  1.5354788  -5.00194838 -5.90185321]
Episodes finished after 75 time steps
[ 1.34351543  1.37948373 -5.11998544 -5.55328058]
Episodes finished after 76 time steps
[ 1.3711051   1.58437225 -5.23105105 -5.40519407]
Episodes finished after 77 time steps
[ 1.40279255  1.41706452 -5.3391

[-0.8722704  -2.07145109  5.22596931  3.63593125]
Episodes finished after 68 time steps
[-0.91369942 -2.26114025  5.29868794  3.51965097]
Episodes finished after 69 time steps
[-0.95892223 -2.07873692  5.36908096  3.12337002]
Episodes finished after 70 time steps
[-1.00049696 -2.26587301  5.43154836  3.06188721]
Episodes finished after 71 time steps
[-1.04581442 -2.45301738  5.4927861   3.02561616]
Episodes finished after 72 time steps
[-1.09487477 -2.26405422  5.55329843  2.61726885]
Episodes finished after 73 time steps
[-1.14015586 -2.07249365  5.6056438   2.20709324]
Episodes finished after 74 time steps
[-1.18160573 -1.87891269  5.64978567  1.79655757]
Episodes finished after 75 time steps
[-1.21918398 -1.68381377  5.68571682  1.38666195]
Episodes finished after 76 time steps
[-1.25286026 -1.48762001  5.71345006  0.97796344]
Episodes finished after 77 time steps
[-1.28261266 -1.67278906  5.73300933  1.05325783]
Episodes finished after 78 time steps
[-1.31606844 -1.47578174  5.7540

[ 0.65119267  0.27158496 -6.19984091 -5.55421346]
Episodes finished after 81 time steps
[ 0.65662436  0.07787698 -6.31092518 -5.24018518]
Episodes finished after 82 time steps
[ 0.6581819  -0.11757939 -6.41572889 -4.9552679 ]
Episodes finished after 83 time steps
[ 0.65583032 -0.31373788 -6.51483424 -4.70246476]
Episodes finished after 84 time steps
[ 0.64955556 -0.12110722 -6.60888354 -5.05119008]
Episodes finished after 85 time steps
[ 0.64713341  0.06897361 -6.70990734 -5.41539308]
Episodes finished after 86 time steps
[ 0.64851289 -0.13009154 -6.8182152  -5.26525478]
Episodes finished after 87 time steps
[ 0.64591106 -0.32893107 -6.9235203  -5.15857704]
Episodes finished after 88 time steps
[ 0.63933243 -0.14719613 -7.02669184 -5.55283017]
Episodes finished after 89 time steps
[ 0.63638851 -0.3487764  -7.13774844 -5.52925616]
Episodes finished after 90 time steps
[ 0.62941298 -0.17623324 -7.24833357 -5.92094003]
Episodes finished after 91 time steps
[ 0.62588832 -0.3825578  -7.3667

array([0.00830886, 0.02003006, 0.00122797, 0.03725499])

In [6]:
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(4,)


In [7]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


# 2. Defining parameter

In [11]:
#Training Parameters

n_epsd = 1000
n_win_ticks = 195
max_env_steps = None
gamma = 1.0
epsilon = 1.0
epsilon_min = 0.01
epsilon_decay = 0.995
alpha = 0.01 
alpha_decay = 0.01
batch_size = 64
monitor = False
quiet = False

#Environment Parameters

memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None:
    env.max_episode_steps = max_env_steps


# Building  Neural Network

In [14]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


In [15]:
#Model Definition

model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(24, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))


# Defining necessary functions

In [16]:
def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

In [ ]:
import random
import gym
import math
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Training Parameters
n_episodes=1000
n_win_ticks=195
max_env_steps=None
gamma=1.0
epsilon=1.0
epsilon_min=0.01
epsilon_decay=0.995
alpha=0.01
alpha_decay=0.01
batch_size=64
monitor=False
quiet=False

# Environment Parameters
memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Definition
model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(48, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))

def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay    
        
def run():
    scores = deque(maxlen=100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 20 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, get_epsilon(e))

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e

run()

[Episode 0] - Mean survival time over last 100 episodes was 12.0 ticks.
[Episode 20] - Mean survival time over last 100 episodes was 9.666666666666666 ticks.
[Episode 40] - Mean survival time over last 100 episodes was 9.487804878048781 ticks.
[Episode 60] - Mean survival time over last 100 episodes was 9.40983606557377 ticks.
[Episode 80] - Mean survival time over last 100 episodes was 9.382716049382717 ticks.
[Episode 100] - Mean survival time over last 100 episodes was 9.36 ticks.
[Episode 120] - Mean survival time over last 100 episodes was 9.5 ticks.
[Episode 140] - Mean survival time over last 100 episodes was 9.87 ticks.
[Episode 160] - Mean survival time over last 100 episodes was 9.98 ticks.
[Episode 180] - Mean survival time over last 100 episodes was 10.14 ticks.
[Episode 200] - Mean survival time over last 100 episodes was 10.36 ticks.
[Episode 220] - Mean survival time over last 100 episodes was 10.44 ticks.
[Episode 240] - Mean survival time over last 100 episodes was 10.