In [1]:
import keras
import gym

print(gym.__version__)
print(keras.__version__)
print(keras.backend.backend())

Using TensorFlow backend.


0.15.3
2.3.1
tensorflow


In [2]:
import math
import random
import numpy as np
from collections import deque

In [3]:
#using gym to run an environment 

env = gym.make('CartPole-v0')
for i_epsd in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episodes finished after {} time steps".format(t+1))
env.reset()

[ 0.04079263  0.02655443  0.00596583 -0.03848714]
[ 0.04132372 -0.16865256  0.00519609  0.25607207]
[ 0.03795067  0.02639482  0.01031753 -0.0349674 ]
[ 0.03847856  0.22136731  0.00961818 -0.32437727]
[ 0.04290591  0.416351    0.00313063 -0.61401157]
[ 0.05123293  0.22118544 -0.0091496  -0.32034426]
[ 0.05565664  0.41643649 -0.01555648 -0.61589853]
[ 0.06398537  0.2215353  -0.02787445 -0.32815554]
[ 0.06841607  0.41704276 -0.03443756 -0.62949684]
[ 0.07675693  0.61262793 -0.0470275  -0.93282329]
[ 0.08900949  0.80835177 -0.06568397 -1.23990545]
[ 0.10517652  1.00425282 -0.09048207 -1.55242056]
[ 0.12526158  0.81032485 -0.12153049 -1.289284  ]
[ 0.14146808  0.61694007 -0.14731617 -1.03698845]
[ 0.15380688  0.42405051 -0.16805594 -0.79394248]
[ 0.16228789  0.23158475 -0.18393478 -0.55848728]
[ 0.16691958  0.03945622 -0.19510453 -0.32892824]
[ 0.16770871  0.23674276 -0.20168309 -0.676241  ]
Episodes finished after 18 time steps
[ 0.17244356  0.43401076 -0.21520792 -1.02503898]
Episodes fin

c:\python\lib\site-packages\gym\logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


[ 0.22036459  0.46104102 -0.38941312 -1.71802185]
Episodes finished after 27 time steps
[ 0.22958541  0.65802932 -0.42377355 -2.1029979 ]
Episodes finished after 28 time steps
[ 0.24274599  0.85432403 -0.46583351 -2.49228845]
Episodes finished after 29 time steps
[ 0.25983247  1.04959669 -0.51567928 -2.88604254]
Episodes finished after 30 time steps
[ 0.28082441  0.85999366 -0.57340013 -2.78360156]
Episodes finished after 31 time steps
[ 0.29802428  1.05338595 -0.62907216 -3.18678613]
Episodes finished after 32 time steps
[ 0.319092    1.24465593 -0.69280789 -3.59175804]
Episodes finished after 33 time steps
[ 0.34398512  1.43316059 -0.76464305 -3.99710487]
Episodes finished after 34 time steps
[ 0.37264833  1.24114592 -0.84458514 -3.99278985]
Episodes finished after 35 time steps
[ 0.39747125  1.04936039 -0.92444094 -4.02158206]
Episodes finished after 36 time steps
[ 0.41845846  0.85748474 -1.00487258 -4.08293302]
Episodes finished after 37 time steps
[ 0.43560815  0.66515259 -1.0865

[-0.34193814 -0.06756701  0.97238317  3.25095969]
Episodes finished after 35 time steps
[-0.34328948 -0.25164982  1.03740237  3.6494211 ]
Episodes finished after 36 time steps
[-0.34832247 -0.43207368  1.11039079  4.04018763]
Episodes finished after 37 time steps
[-0.35696395 -0.23969136  1.19119454  4.17535761]
Episodes finished after 38 time steps
[-0.36175777 -0.41301103  1.27470169  4.54476398]
Episodes finished after 39 time steps
[-0.37001799 -0.58157735  1.36559697  4.89974827]
Episodes finished after 40 time steps
[-0.38164954 -0.38048864  1.46359194  5.12611881]
Episodes finished after 41 time steps
[-0.38925931 -0.54010198  1.56611432  5.44404873]
Episodes finished after 42 time steps
[-0.40006135 -0.69503992  1.67499529  5.73913363]
Episodes finished after 43 time steps
[-0.41396215 -0.48190119  1.78977796  6.06479204]
Episodes finished after 44 time steps
[-0.42360018 -0.62871866  1.9110738   6.30393009]
Episodes finished after 45 time steps
[-0.43617455 -0.40695649  2.0371

[ 0.32355958  0.24711395 -1.15228502 -4.07721272]
Episodes finished after 46 time steps
[ 0.32850186  0.42205629 -1.23382928 -4.45248407]
Episodes finished after 47 time steps
[ 0.33694299  0.22593745 -1.32287896 -4.63268698]
Episodes finished after 48 time steps
[ 0.34146173  0.02756966 -1.4155327  -4.84468322]
Episodes finished after 49 time steps
[ 0.34201313  0.19061483 -1.51242636 -5.17296673]
Episodes finished after 50 time steps
[ 0.34582542  0.34896255 -1.6158857  -5.48032229]
Episodes finished after 51 time steps
[ 0.35280468  0.50292449 -1.72549214 -5.76361394]
Episodes finished after 52 time steps
[ 0.36286317  0.65311262 -1.84076442 -6.01939174]
Episodes finished after 53 time steps
[ 0.37592542  0.43505584 -1.96115226 -6.38997673]
Episodes finished after 54 time steps
[ 0.38462653  0.57926772 -2.08895179 -6.57954745]
Episodes finished after 55 time steps
[ 0.39621189  0.7235603  -2.22054274 -6.72775778]
Episodes finished after 56 time steps
[ 0.41068309  0.49688451 -2.3550

[ 1.24641681  1.50001908 -4.25248633 -7.23982643]
Episodes finished after 54 time steps
[ 1.27641719  1.3643934  -4.39728285 -7.0666727 ]
Episodes finished after 55 time steps
[ 1.30370506  1.22878768 -4.53861631 -6.85018808]
Episodes finished after 56 time steps
[ 1.32828082  1.45536013 -4.67562007 -6.5018545 ]
Episodes finished after 57 time steps
[ 1.35738802  1.67609461 -4.80565716 -6.19588171]
Episodes finished after 58 time steps
[ 1.39090991  1.89154839 -4.92957479 -5.93325832]
Episodes finished after 59 time steps
[ 1.42874088  2.10247375 -5.04823996 -5.7143411 ]
Episodes finished after 60 time steps
[ 1.47079035  2.30969502 -5.16252678 -5.53920854]
Episodes finished after 61 time steps
[ 1.51698425  2.1456391  -5.27331095 -5.16742618]
Episodes finished after 62 time steps
[ 1.55989704  2.3458558  -5.37665948 -5.07824032]
Episodes finished after 63 time steps
[ 1.60681415  2.54480163 -5.47822428 -5.03072515]
Episodes finished after 64 time steps
[ 1.65771019  2.74302009 -5.5788

[-0.84463226 -0.47771222 -0.60944516 -2.80744496]
Episodes finished after 74 time steps
[-0.85418651 -0.66599051 -0.66559406 -2.74416164]
Episodes finished after 75 time steps
[-0.86750632 -0.47380211 -0.72047729 -3.15246314]
Episodes finished after 76 time steps
[-0.87698236 -0.66220984 -0.78352655 -3.13404766]
Episodes finished after 77 time steps
[-0.89022655 -0.85007694 -0.84620751 -3.14191186]
Episodes finished after 78 time steps
[-0.90722809 -1.03759952 -0.90904574 -3.17560811]
Episodes finished after 79 time steps
[-0.92798008 -1.22499647 -0.97255791 -3.2348171 ]
Episodes finished after 80 time steps
[-0.95248001 -1.41251136 -1.03725425 -3.3193487 ]
Episodes finished after 81 time steps
[-0.98073024 -1.2302512  -1.10364122 -3.71152847]
Episodes finished after 82 time steps
[-1.00533526 -1.42050816 -1.17787179 -3.84550451]
Episodes finished after 83 time steps
[-1.03374543 -1.24462403 -1.25478188 -4.21811658]
Episodes finished after 84 time steps
[-1.05863791 -1.07310287 -1.3391

[-0.23368177  0.34423387  6.2873112   3.66816035]
Episodes finished after 82 time steps
[-0.2267971   0.53935057  6.36067441  3.37670081]
Episodes finished after 83 time steps
[-0.21601008  0.34406851  6.42820842  3.6915039 ]
Episodes finished after 84 time steps
[-0.20912871  0.53876344  6.5020385   3.4450147 ]
Episodes finished after 85 time steps
[-0.19835345  0.3437884   6.57093879  3.7943316 ]
Episodes finished after 86 time steps
[-0.19147768  0.53785013  6.64682543  3.59864446]
Episodes finished after 87 time steps
[-0.18072068  0.34424668  6.71879831  3.97462908]
Episodes finished after 88 time steps
[-0.17383574  0.15263813  6.7982909   4.35925894]
Episodes finished after 89 time steps
[-0.17078298 -0.03614666  6.88547608  4.75052351]
Episodes finished after 90 time steps
[-0.17150591 -0.22114583  6.98048655  5.14575389]
Episodes finished after 91 time steps
[-0.17592883 -0.40130303  7.08340162  5.54170316]
Episodes finished after 92 time steps
[-0.18395489 -0.57553192  7.1942

[-1.96279164 -1.90630204  7.80517294  7.68337263]
Episodes finished after 87 time steps
[-2.00091768 -2.03518881  7.95884039  7.98645495]
Episodes finished after 88 time steps
[-2.04162145 -1.79413305  8.11856949  8.31668588]
Episodes finished after 89 time steps
[-2.07750411 -1.54709871  8.28490321  8.69735827]
Episodes finished after 90 time steps
[-2.10844609 -1.29472572  8.45885038  9.12260858]
Episodes finished after 91 time steps
[-2.1343406  -1.41061485  8.64130255  9.2655949 ]
Episodes finished after 92 time steps
[-2.1625529  -1.53492432  8.82661445  9.34098081]
Episodes finished after 93 time steps
[-2.19325139 -1.29085523  9.01343406  9.8090773 ]
Episodes finished after 94 time steps
[-2.21906849 -1.05569461  9.20961561 10.24994749]
Episodes finished after 95 time steps
[-2.24018238 -1.22537506  9.41461456 10.06406639]
Episodes finished after 96 time steps
[-2.26468988 -1.41934552  9.61589589  9.77611372]
Episodes finished after 97 time steps
[-2.29307679 -1.63428644  9.8114

Episodes finished after 96 time steps
[ 0.51323701  0.72366974  5.1228824  -0.72485242]
Episodes finished after 97 time steps
[ 0.52771041  0.5443565   5.10838535 -0.88709248]
Episodes finished after 98 time steps
[ 0.53859754  0.73217579  5.0906435  -1.26701126]
Episodes finished after 99 time steps
[ 0.55324106  0.91896094  5.06530327 -1.64369792]
Episodes finished after 100 time steps
[ 0.01311732 -0.03076313 -0.00485229  0.03423952]
[ 0.01250206  0.16442807 -0.0041675  -0.2599704 ]
[ 0.01579062 -0.03063414 -0.00936691  0.03139514]
[ 0.01517794 -0.22562052 -0.008739    0.32110805]
[ 0.01066553 -0.42061694 -0.00231684  0.61102227]
[ 0.00225319 -0.61570643  0.0099036   0.90297457]
[-0.01006094 -0.42072002  0.0279631   0.61342092]
[-0.01847534 -0.22599977  0.04023151  0.3296748 ]
[-0.02299533 -0.42167065  0.04682501  0.6347685 ]
[-0.03142875 -0.22723203  0.05952038  0.35719177]
[-0.03597339 -0.42314744  0.06666422  0.66803316]
[-0.04443634 -0.61912999  0.08002488  0.98093876]
[-0.05681

[ 0.02034136 -0.35080633  0.0531121   0.59381646]
[ 0.01332523 -0.15646646  0.06498843  0.31832534]
[ 0.0101959  -0.35245092  0.07135494  0.63077459]
[ 0.00314688 -0.54849215  0.08397043  0.9450487 ]
[-0.00782296 -0.35459553  0.1028714   0.67988684]
[-0.01491487 -0.55098457  0.11646914  1.00310395]
[-0.02593456 -0.3575949   0.13653122  0.74914929]
[-0.03308646 -0.16459386  0.1515142   0.50235739]
[-0.03637834 -0.36149027  0.16156135  0.83869337]
[-0.04360814 -0.55840592  0.17833522  1.17751296]
[-0.05477626 -0.75533817  0.20188548  1.52037952]
Episodes finished after 13 time steps
[-0.06988303 -0.95224592  0.23229307  1.86869439]
Episodes finished after 14 time steps
[-0.08892794 -1.14903335  0.26966696  2.2236289 ]
Episodes finished after 15 time steps
[-0.11190861 -0.95730459  0.31413953  2.02475414]
Episodes finished after 16 time steps
[-0.1310547  -0.76649444  0.35463462  1.84339102]
Episodes finished after 17 time steps
[-0.14638459 -0.57656717  0.39150244  1.67831873]
Episodes f

[ 0.08240545  1.56852756 -0.11397823 -2.31165311]
[ 0.113776    1.76449161 -0.1602113  -2.637129  ]
Episodes finished after 10 time steps
[ 0.14906583  1.57090632 -0.21295388 -2.39737065]
Episodes finished after 11 time steps
[ 0.18048396  1.37819173 -0.26090129 -2.17696495]
Episodes finished after 12 time steps
[ 0.2080478   1.18638518 -0.30444059 -1.97482955]
Episodes finished after 13 time steps
[ 0.2317755   0.99547916 -0.34393718 -1.78976811]
Episodes finished after 14 time steps
[ 0.25168508  1.19246119 -0.37973254 -2.16707229]
Episodes finished after 15 time steps
[ 0.27553431  1.00248812 -0.42307399 -2.01138972]
Episodes finished after 16 time steps
[ 0.29558407  1.19893556 -0.46330178 -2.40078628]
Episodes finished after 17 time steps
[ 0.31956278  1.39442128 -0.51131751 -2.79449308]
Episodes finished after 18 time steps
[ 0.34745121  1.58853442 -0.56720737 -3.19228439]
Episodes finished after 19 time steps
[ 0.37922189  1.39858171 -0.63105306 -3.10993386]
Episodes finished af

[ 0.02494562  0.38383521  0.03381788 -0.53266443]
[ 0.03262232  0.57846561  0.02316459 -0.81450254]
[ 0.04419163  0.38303423  0.00687454 -0.51462434]
[ 0.05185232  0.18781614 -0.00341795 -0.21978303]
[ 0.05560864  0.38298678 -0.00781361 -0.51354215]
[ 0.06326838  0.18797575 -0.01808445 -0.22333171]
[ 0.06702789 -0.00688312 -0.02255109  0.06359226]
[ 0.06689023 -0.20167461 -0.02127924  0.34907574]
[ 0.06285674 -0.00625658 -0.01429773  0.04975943]
[ 0.06273161 -0.20117063 -0.01330254  0.33789723]
[ 0.05870819 -0.39610078 -0.00654459  0.62635576]
[ 0.05078618 -0.20088809  0.00598252  0.3316189 ]
[ 0.04676842 -0.39609468  0.0126149   0.6261824 ]
[ 0.03884652 -0.59139043  0.02513855  0.9228114 ]
[ 0.02701871 -0.78684284  0.04359478  1.22328733]
[ 0.01128186 -0.98249839  0.06806052  1.52930463]
[-0.00836811 -0.78826007  0.09864662  1.25861606]
[-0.02413331 -0.59452899  0.12381894  0.9983873 ]
[-0.03602389 -0.79106914  0.14378668  1.32725034]
[-0.05184527 -0.98768324  0.17033169  1.66125582]


[ 0.0869008   0.023428   -0.22728028 -0.43922564]
Episodes finished after 15 time steps
[ 0.08736936  0.22092227 -0.2360648  -0.79409516]
Episodes finished after 16 time steps
[ 0.09178781  0.02968298 -0.2519467  -0.58395225]
Episodes finished after 17 time steps
[ 0.09238147  0.22728576 -0.26362575 -0.9442898 ]
Episodes finished after 18 time steps
[ 0.09692718  0.03649311 -0.28251154 -0.74459954]
Episodes finished after 19 time steps
[ 0.09765704  0.23417964 -0.29740353 -1.11133234]
Episodes finished after 20 time steps
[ 0.10234064  0.43172537 -0.31963018 -1.48079611]
Episodes finished after 21 time steps
[ 0.11097514  0.24158294 -0.3492461  -1.3024074 ]
Episodes finished after 22 time steps
[ 0.1158068   0.05212914 -0.37529425 -1.13598615]
Episodes finished after 23 time steps
[ 0.11684939 -0.13670691 -0.39801397 -0.98021122]
Episodes finished after 24 time steps
[ 0.11411525  0.06100257 -0.4176182  -1.36754475]
Episodes finished after 25 time steps
[ 0.1153353  -0.1272764  -0.4449

[-0.00191754 -0.20924581  0.10543881  0.5612528 ]
[-0.00610246 -0.0157493   0.11666387  0.30356152]
[-0.00641744  0.17753351  0.1227351   0.0498295 ]
[-0.00286677  0.37070133  0.12373169 -0.20174898]
[0.00454725 0.17404702 0.11969671 0.12726173]
[ 0.00802819  0.36726898  0.12224195 -0.12539057]
[ 0.01537357  0.56044692  0.11973413 -0.37714547]
[ 0.02658251  0.363846    0.11219122 -0.04923767]
[0.03385943 0.16730904 0.11120647 0.27662944]
[ 0.03720561 -0.02920928  0.11673906  0.60221341]
[ 0.03662143 -0.22575396  0.12878333  0.92926721]
[ 0.03210635 -0.42235703  0.14736867  1.2594874 ]
[ 0.02365921 -0.61902448  0.17255842  1.59446076]
[ 0.01127872 -0.42631827  0.20444764  1.36017513]
Episodes finished after 27 time steps
[ 0.00275235 -0.62333062  0.23165114  1.70922871]
Episodes finished after 28 time steps
[-0.00971426 -0.43149879  0.26583571  1.49666505]
Episodes finished after 29 time steps
[-0.01834424 -0.62868615  0.29576901  1.8592947 ]
Episodes finished after 30 time steps
[-0.03

[-0.51889659 -1.91034948  1.10276475  4.97722219]
Episodes finished after 27 time steps
[-0.55710358 -1.71104737  1.2023092   5.10473799]
Episodes finished after 28 time steps
[-0.59132452 -1.50984053  1.30440396  5.27028933]
Episodes finished after 29 time steps
[-0.62152133 -1.6714561   1.40980974  5.61773766]
Episodes finished after 30 time steps
[-0.65495046 -1.46306824  1.5221645   5.85783173]
Episodes finished after 31 time steps
[-0.68421182 -1.25070688  1.63932113  6.13599896]
Episodes finished after 32 time steps
[-0.70922596 -1.39751173  1.76204111  6.41423112]
Episodes finished after 33 time steps
[-0.73717619 -1.54046797  1.89032573  6.6621111 ]
Episodes finished after 34 time steps
[-0.76798555 -1.68093936  2.02356796  6.87504253]
Episodes finished after 35 time steps
[-0.80160434 -1.45224051  2.16106881  7.28948828]
Episodes finished after 36 time steps
[-0.83064915 -1.21918823  2.30685857  7.7283112 ]
Episodes finished after 37 time steps
[-0.85503292 -0.98322854  2.4614

[ 0.9009976   2.06716317 -1.886458   -7.40940194]
Episodes finished after 37 time steps
[ 0.94234086  2.19845793 -2.03464604 -7.62773594]
Episodes finished after 38 time steps
[ 0.98631002  2.32941202 -2.18720076 -7.80278878]
Episodes finished after 39 time steps
[ 1.03289826  2.09068789 -2.34325653 -8.24969314]
Episodes finished after 40 time steps
[ 1.07471202  2.22600903 -2.50825039 -8.31859393]
Episodes finished after 41 time steps
[ 1.1192322   1.99013487 -2.67462227 -8.77778645]
Episodes finished after 42 time steps
[ 1.1590349   1.75883742 -2.850178   -9.2199411 ]
Episodes finished after 43 time steps
[ 1.19421165  1.92518043 -3.03457682 -9.06541492]
Episodes finished after 44 time steps
[ 1.23271526  1.7201427  -3.21588512 -9.40261471]
Episodes finished after 45 time steps
[ 1.26711811  1.9226466  -3.40393742 -9.07787484]
Episodes finished after 46 time steps
[ 1.30557104  2.14113625 -3.58549491 -8.68510629]
Episodes finished after 47 time steps
[ 1.34839377  1.98528489 -3.7591

[-0.02578334 -0.24065082  0.87291866  3.46011561]
Episodes finished after 50 time steps
[-0.03059636 -0.42592555  0.94212097  3.86396503]
Episodes finished after 51 time steps
[-0.03911487 -0.23498344  1.01940027  3.93332225]
Episodes finished after 52 time steps
[-0.04381454 -0.41413721  1.09806672  4.32453146]
Episodes finished after 53 time steps
[-0.05209728 -0.58870343  1.18455735  4.70551289]
Episodes finished after 54 time steps
[-0.06387135 -0.7581786   1.27866761  5.07361838]
Episodes finished after 55 time steps
[-0.07903492 -0.55649546  1.38013997  5.26803796]
Episodes finished after 56 time steps
[-0.09016483 -0.35189073  1.48550073  5.49855076]
Episodes finished after 57 time steps
[-0.09720265 -0.50753468  1.59547175  5.81137141]
Episodes finished after 58 time steps
[-0.10735334 -0.29468554  1.71169918  6.11315933]
Episodes finished after 59 time steps
[-0.11324705 -0.0770799   1.83396236  6.45008552]
Episodes finished after 60 time steps
[-0.11478865  0.14564195  1.9629

[-1.1098077  -1.95065988  3.7876789   6.29766679]
Episodes finished after 63 time steps
[-1.1488209  -1.78998952  3.91363224  6.31308933]
Episodes finished after 64 time steps
[-1.18462069 -1.63469035  4.03989402  6.2749008 ]
Episodes finished after 65 time steps
[-1.2173145  -1.8569013   4.16539204  5.83727744]
Episodes finished after 66 time steps
[-1.25445252 -1.70466818  4.28213759  5.70494519]
Episodes finished after 67 time steps
[-1.28854589 -1.55300806  4.39623649  5.53262607]
Episodes finished after 68 time steps
[-1.31960605 -1.76663127  4.50688901  5.15357005]
Episodes finished after 69 time steps
[-1.35493867 -1.97534834  4.60996041  4.80187093]
Episodes finished after 70 time steps
[-1.39444564 -2.17952325  4.70599783  4.47809666]
Episodes finished after 71 time steps
[-1.43803611 -2.01601997  4.79555977  4.18567011]
Episodes finished after 72 time steps
[-1.47835651 -1.84888886  4.87927317  3.87185977]
Episodes finished after 73 time steps
[-1.51533428 -2.04232107  4.9567

[-0.06041946  0.02317191  5.9959503   4.26485451]
Episodes finished after 72 time steps
[-0.05995602  0.21603048  6.08124739  3.90412785]
Episodes finished after 73 time steps
[-0.05563542  0.41041572  6.15932995  3.55950787]
Episodes finished after 74 time steps
[-0.0474271   0.21574225  6.2305201   3.81296075]
Episodes finished after 75 time steps
[-0.04311226  0.41083188  6.30677932  3.50525562]
Episodes finished after 76 time steps
[-0.03489562  0.21566243  6.37688443  3.80486432]
Episodes finished after 77 time steps
[-0.03058237  0.02065092  6.45298172  4.12360569]
Episodes finished after 78 time steps
[-0.03016935 -0.17365036  6.53545383  4.4605469 ]
Episodes finished after 79 time steps
[-0.03364236 -0.36651441  6.62466477  4.81406917]
Episodes finished after 80 time steps
[-0.04097265 -0.55702677  6.72094615  5.18179266]
Episodes finished after 81 time steps
[-0.05211318 -0.35891122  6.82458201  5.03727214]
Episodes finished after 82 time steps
[-0.05929141 -0.16120752  6.9253

[ 1.29027223  2.73240741 -5.39710824 -1.62079898]
Episodes finished after 76 time steps
[ 1.34492038  2.54066288 -5.42952422 -1.21116272]
Episodes finished after 77 time steps
[ 1.39573364  2.72221337 -5.45374748 -1.16855754]
Episodes finished after 78 time steps
[ 1.45017791  2.52863614 -5.47711863 -0.755636  ]
Episodes finished after 79 time steps
[ 1.50075063  2.33416053 -5.49223135 -0.34152912]
Episodes finished after 80 time steps
[ 1.54743384  2.13916254 -5.49906193  0.07318638]
Episodes finished after 81 time steps
[ 1.59021709  1.94399562 -5.4975982   0.48808009]
Episodes finished after 82 time steps
[ 1.629097    2.12546942 -5.4878366   0.5035631 ]
Episodes finished after 83 time steps
[ 1.67160639  2.30683149 -5.47776534  0.52307087]
Episodes finished after 84 time steps
[ 1.71774302  2.11214486 -5.46730392  0.93740145]
Episodes finished after 85 time steps
[ 1.75998592  1.91802457 -5.44855589  1.35105504]
Episodes finished after 86 time steps
[ 1.79834641  2.10001739 -5.4215

array([-0.0401177 ,  0.01329031,  0.02704641, -0.03496219])

In [4]:
print(env.action_space)
print(env.observation_space)

Discrete(2)
Box(4,)


In [5]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


# 2. Defining parameter

In [6]:
#Training Parameters

n_epsd = 1000
n_win_ticks = 195
max_env_steps = None
gamma = 1.0
epsilon = 1.0
epsilon_min = 0.01
epsilon_decay = 0.995
alpha = 0.01 
alpha_decay = 0.01
batch_size = 64
monitor = False
quiet = False

#Environment Parameters

memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None:
    env.max_episode_steps = max_env_steps


# Building  Neural Network

In [7]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam


In [8]:
#Model Definition

model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(24, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))


# Defining necessary functions

In [9]:
def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

In [ ]:
import random
import gym
import math
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Training Parameters
n_episodes=1000
n_win_ticks=195
max_env_steps=None
gamma=1.0
epsilon=1.0
epsilon_min=0.01
epsilon_decay=0.995
alpha=0.01
alpha_decay=0.01
batch_size=64
monitor=False
quiet=False

# Environment Parameters
memory = deque(maxlen=100000)
env = gym.make('CartPole-v0')
if max_env_steps is not None: env.max_episode_steps = max_env_steps

from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

# Model Definition
model = Sequential()
model.add(Dense(24, input_dim=4, activation='relu'))
model.add(Dense(48, activation='relu'))
model.add(Dense(2, activation='relu'))
model.compile(loss='mse', optimizer=Adam(lr=alpha, decay=alpha_decay))

def remember(state, action, reward, next_state, done):
    memory.append((state, action, reward, next_state, done))

def choose_action(state, epsilon):
    return env.action_space.sample() if (np.random.random() <= epsilon) else np.argmax(
        model.predict(state))

def get_epsilon(t):
    return max(epsilon_min, min(epsilon, 1.0 - math.log10((t + 1) * epsilon_decay)))

def preprocess_state(state):
    return np.reshape(state, [1, 4])

def replay(batch_size, epsilon):
    x_batch, y_batch = [], []
    minibatch = random.sample(
        memory, min(len(memory), batch_size))
    for state, action, reward, next_state, done in minibatch:
        y_target = model.predict(state)
        y_target[0][action] = reward if done else reward + gamma * np.max(model.predict(next_state)[0])
        x_batch.append(state[0])
        y_batch.append(y_target[0])

    model.fit(np.array(x_batch), np.array(y_batch), batch_size=len(x_batch), verbose=0)
    
    if epsilon > epsilon_min:
        epsilon *= epsilon_decay    
        
def run():
    scores = deque(maxlen=100)

    for e in range(n_episodes):
        state = preprocess_state(env.reset())
        done = False
        i = 0
        while not done:
            action = choose_action(state, get_epsilon(e))
            next_state, reward, done, _ = env.step(action)
            env.render()
            next_state = preprocess_state(next_state)
            remember(state, action, reward, next_state, done)
            state = next_state
            i += 1

        scores.append(i)
        mean_score = np.mean(scores)
        if mean_score >= n_win_ticks and e >= 100:
            if not quiet: print('Ran {} episodes. Solved after {} trials'.format(e, e - 100))
            return e - 100
        if e % 20 == 0 and not quiet:
            print('[Episode {}] - Mean survival time over last 100 episodes was {} ticks.'.format(e, mean_score))
   
        replay(batch_size, get_epsilon(e))

    if not quiet: print('Did not solve after {} episodes'.format(e))
    return e

run()

[Episode 0] - Mean survival time over last 100 episodes was 21.0 ticks.
[Episode 20] - Mean survival time over last 100 episodes was 10.761904761904763 ticks.
[Episode 40] - Mean survival time over last 100 episodes was 9.975609756097562 ticks.
[Episode 60] - Mean survival time over last 100 episodes was 10.60655737704918 ticks.
[Episode 80] - Mean survival time over last 100 episodes was 10.679012345679013 ticks.
[Episode 100] - Mean survival time over last 100 episodes was 10.91 ticks.
[Episode 120] - Mean survival time over last 100 episodes was 11.44 ticks.
[Episode 140] - Mean survival time over last 100 episodes was 12.39 ticks.
[Episode 160] - Mean survival time over last 100 episodes was 13.31 ticks.
[Episode 180] - Mean survival time over last 100 episodes was 16.34 ticks.
[Episode 200] - Mean survival time over last 100 episodes was 17.31 ticks.
[Episode 220] - Mean survival time over last 100 episodes was 18.54 ticks.
[Episode 240] - Mean survival time over last 100 episodes